/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tbmctdXNlci1mb3JtL25nLWFkbWluLW5nLXVzZXItZm9ybS5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vQ29tcG9uZW50cy9uZy1hZG1pbi1uZy11c2VyLWZvcm0vbmctYWRtaW4tbmctdXNlci1mb3JtLmNvbXBvbmVudC5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
