/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin-ng-user-form.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './ng-admin-ng-user-form.component';
const styles_NgAdminNgUserFormComponent:any[] = [i0.styles];
export const RenderType_NgAdminNgUserFormComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminNgUserFormComponent,data:{}});
export function View_NgAdminNgUserFormComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  ngadmin-nguser-form works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_NgAdminNgUserFormComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-ng-user-form',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminNgUserFormComponent_0,
      RenderType_NgAdminNgUserFormComponent)),i1.ɵdid(49152,(null as any),0,i2.NgAdminNgUserFormComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NgAdminNgUserFormComponentNgFactory:i1.ComponentFactory<i2.NgAdminNgUserFormComponent> = i1.ɵccf('app-ng-admin-ng-user-form',
    i2.NgAdminNgUserFormComponent,View_NgAdminNgUserFormComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tbmctdXNlci1mb3JtL25nLWFkbWluLW5nLXVzZXItZm9ybS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tbmctdXNlci1mb3JtL25nLWFkbWluLW5nLXVzZXItZm9ybS5jb21wb25lbnQudHMiLCJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vQ29tcG9uZW50cy9uZy1hZG1pbi1uZy11c2VyLWZvcm0vbmctYWRtaW4tbmctdXNlci1mb3JtLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tbmctdXNlci1mb3JtL25nLWFkbWluLW5nLXVzZXItZm9ybS5jb21wb25lbnQudHMuTmdBZG1pbk5nVXNlckZvcm1Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgbmdhZG1pbi1uZ3VzZXItZm9ybSB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtbmctYWRtaW4tbmctdXNlci1mb3JtPjwvYXBwLW5nLWFkbWluLW5nLXVzZXItZm9ybT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLHNEQUVDO01BQUE7OztvQkNGSjtNQUFBOzJDQUFBLFVBQUE7TUFBQTs7OyJ9
