/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ng-admin-routing.module';
import * as i2 from './ng-admin.component.ngfactory';
import * as i3 from './Components/ng-admin-home/ng-admin-home.component.ngfactory';
import * as i4 from './Components/ng-admin-ng-user/ng-admin-ng-user.component.ngfactory';
import * as i5 from './Components/ng-admin-kategori/ng-admin-kategori.component.ngfactory';
import * as i6 from './Components/ng-admin-barang/ng-admin-barang.component.ngfactory';
import * as i7 from './Components/ng-admin-transaksi/ng-admin-transaksi.component.ngfactory';
import * as i8 from './Components/ng-admin-testimoni/ng-admin-testimoni.component.ngfactory';
import * as i9 from '@angular/router';
import * as i10 from './ng-admin.component';
import * as i11 from './Guards/ngadmin-children/ngadmin-children.guard';
import * as i12 from './Components/ng-admin-home/ng-admin-home.component';
import * as i13 from './Components/ng-admin-ng-user/ng-admin-ng-user.component';
import * as i14 from './Components/ng-admin-kategori/ng-admin-kategori.component';
import * as i15 from './Components/ng-admin-barang/ng-admin-barang.component';
import * as i16 from './Components/ng-admin-transaksi/ng-admin-transaksi.component';
import * as i17 from './Components/ng-admin-testimoni/ng-admin-testimoni.component';
export const NgAdminRoutingModuleNgFactory:i0.NgModuleFactory<i1.NgAdminRoutingModule> = i0.ɵcmf(i1.NgAdminRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.NgAdminComponentNgFactory,i3.NgAdminHomeComponentNgFactory,i4.NgAdminNgUserComponentNgFactory,
              i5.NgAdminKategoriComponentNgFactory,i6.NgAdminBarangComponentNgFactory,
              i7.NgAdminTransaksiComponentNgFactory,i8.NgAdminTestimoniComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,i9.RouterModule,
          i9.RouterModule,[[2,i9.ɵa],[2,i9.Router]]),i0.ɵmpd(512,i1.NgAdminRoutingModule,
          i1.NgAdminRoutingModule,([] as any[])),i0.ɵmpd(1024,i9.ROUTES,() => {
        return [[{path:'ngadmin',component:i10.NgAdminComponent,canActivateChild:[i11.NgadminChildrenGuard],
            children:[{path:'dashboard',component:i12.NgAdminHomeComponent},{path:'users',
                component:i13.NgAdminNgUserComponent},{path:'kategori',component:i14.NgAdminKategoriComponent},
                {path:'barang',component:i15.NgAdminBarangComponent},{path:'transaksi',
                    component:i16.NgAdminTransaksiComponent},{path:'testimoni',component:i17.NgAdminTestimoniComponent},
                {path:'**',pathMatch:'full',redirectTo:'/ngadmin/dashboard'}]}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL25nLWFkbWluLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL01vZHVsZXMvbmdBZG1pbi9uZy1hZG1pbi1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
