/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './ng-admin.component';
import * as i3 from './Components/ng-admin-nav/ng-admin-nav.component.ngfactory';
import * as i4 from './Components/ng-admin-nav/ng-admin-nav.component';
import * as i5 from './Components/ng-admin-container/ng-admin-container.component.ngfactory';
import * as i6 from './Components/ng-admin-container/ng-admin-container.component';
const styles_NgAdminComponent:any[] = [i0.styles];
export const RenderType_NgAdminComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminComponent,data:{}});
export function View_NgAdminComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[i1.ɵqud(402653184,1,{_ngAdminContainer_:0}),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),1,'app-ng-admin-nav',([] as any[]),(null as any),
      [[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i2.NgAdminComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.NgadminSidenavToggle()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },i3.View_NgAdminNavComponent_0,i3.RenderType_NgAdminNavComponent)),i1.ɵdid(49152,
      [['ngAdminNav',4]],0,i4.NgAdminNavComponent,([] as any[]),(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'app-ng-admin-container',([] as any[]),(null as any),(null as any),(null as any),
          i5.View_NgAdminContainerComponent_0,i5.RenderType_NgAdminContainerComponent)),
      i1.ɵdid(114688,[[1,4],['ngAdminContainer',4]],0,i6.NgAdminContainerComponent,
          ([] as any[]),(null as any),(null as any)),(_l()(),i1.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    _ck(_v,5,0);
  },(null as any));
}
export function View_NgAdminComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ngadmin',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminComponent_0,
      RenderType_NgAdminComponent)),i1.ɵdid(49152,(null as any),0,i2.NgAdminComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NgAdminComponentNgFactory:i1.ComponentFactory<i2.NgAdminComponent> = i1.ɵccf('app-ngadmin',
    i2.NgAdminComponent,View_NgAdminComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL25nLWFkbWluLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vbmctYWRtaW4uY29tcG9uZW50LnRzIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL25nLWFkbWluLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL25nLWFkbWluLmNvbXBvbmVudC50cy5OZ0FkbWluQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFwcC1uZy1hZG1pbi1uYXYgKGNsaWNrKT0nTmdhZG1pblNpZGVuYXZUb2dnbGUoKScgI25nQWRtaW5OYXY+PC9hcHAtbmctYWRtaW4tbmF2PlxuPGFwcC1uZy1hZG1pbi1jb250YWluZXIgI25nQWRtaW5Db250YWluZXI+PC9hcHAtbmctYWRtaW4tY29udGFpbmVyPlxuIiwiPGFwcC1uZ2FkbWluPjwvYXBwLW5nYWRtaW4+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztnRUNBQTtNQUFBO01BQUE7UUFBQTtRQUFBO1FBQWtCO1VBQUE7VUFBQTtRQUFBO1FBQWxCO01BQUEsMkVBQUE7TUFBQTtNQUFrRix1Q0FDbEY7VUFBQTtxRkFBQTthQUFBO1VBQUEsMkNBQW1FO1VBQUE7SUFBbkU7Ozs7b0JDREE7TUFBQTtpQ0FBQSxVQUFBO01BQUE7OzsifQ==
