/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.ngadmin-container[_ngcontent-%COMP%] {\r\n	background-color: yellow;\r\n	box-sizing: border-box;\r\n	padding-top: 64px;\r\n	height: 100%;\r\n	width: 100%;\r\n	.ngadmin-content{\r\n		padding: 15px;\r\n	}\r\n}\r\n\r\n.mat-sidenav[_ngcontent-%COMP%] {\r\n	min-width: 200px;\r\n	padding-top: 60px;\r\n	background-color: #F5F5F5;\r\n	.mat-button {\r\n		width: 100%;\r\n		position: relative;\r\n		bottom: 0;\r\n		margin: 24px 0;\r\n	}\r\n}\r\n\r\n@media (max-width: 600px){\r\n	.mat-sidenav[_ngcontent-%COMP%]{\r\n		padding-top: 54px;\r\n		min-width: 80vw;\r\n	}\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tY29udGFpbmVyL25nLWFkbWluLWNvbnRhaW5lci5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vQ29tcG9uZW50cy9uZy1hZG1pbi1jb250YWluZXIvbmctYWRtaW4tY29udGFpbmVyLmNvbXBvbmVudC5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
