/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.form.container[_ngcontent-%COMP%]{\r\n	margin-top: 10vh;\r\n}\r\n.mat-card[_ngcontent-%COMP%]{\r\n	background-color: #EEE;\r\n}\r\nspan[_ngcontent-%COMP%]{\r\n	display: inline;\r\n}\r\n.full-width[_ngcontent-%COMP%]{\r\n	width: 100%;\r\n}\r\n.small[_ngcontent-%COMP%]{\r\n	font-size: 10px;\r\n}\r\n.form-error[_ngcontent-%COMP%]{\r\n	background-color: #FF8A65;\r\n	font-size: 13px;\r\n}\r\nbutton[ng-reflect-disabled=\'true\'][_ngcontent-%COMP%]:hover {\r\n	// cursor: none;\r\n	cursor: url(../../../../../assets/Cursors/cursor_click_x.cur) !important;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0F1dGgvQ29tcG9uZW50cy9uZy1hdXRoLW5nYWRtaW4vbmctYXV0aC1uZ2FkbWluLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL01vZHVsZXMvbmdBdXRoL0NvbXBvbmVudHMvbmctYXV0aC1uZ2FkbWluL25nLWF1dGgtbmdhZG1pbi5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
