/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.mat-card-content[_ngcontent-%COMP%]{\r\n	background-color: #E1F5FE;\r\n}\r\n.full-width[_ngcontent-%COMP%]{\r\n	width: 100%;\r\n}\r\n.small[_ngcontent-%COMP%]{\r\n	display: inline;\r\n	font-size: 12px;\r\n	margin: 0;\r\n}\r\n\r\n.keterangan[_ngcontent-%COMP%]{\r\n	color: #000;\r\n	resize: none;\r\n	overflow: auto;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tYmFyYW5nLWZvcm0vbmctYWRtaW4tYmFyYW5nLWZvcm0uY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tYmFyYW5nLWZvcm0vbmctYWRtaW4tYmFyYW5nLWZvcm0uY29tcG9uZW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
