/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ng-auth-routing.module';
import * as i2 from './ng-auth.component.ngfactory';
import * as i3 from './Components/ng-auth-ngadmin/ng-auth-ngadmin.component.ngfactory';
import * as i4 from './Components/ng-auth-user/ng-auth-user.component.ngfactory';
import * as i5 from '@angular/router';
import * as i6 from './ng-auth.component';
import * as i7 from './Components/ng-auth-ngadmin/ng-auth-ngadmin.component';
import * as i8 from './Components/ng-auth-user/ng-auth-user.component';
export const NgAuthRoutingModuleNgFactory:i0.NgModuleFactory<i1.NgAuthRoutingModule> = i0.ɵcmf(i1.NgAuthRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.NgAuthComponentNgFactory,i3.NgAuthNgadminComponentNgFactory,i4.NgAuthUserComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,i5.RouterModule,
          i5.RouterModule,[[2,i5.ɵa],[2,i5.Router]]),i0.ɵmpd(512,i1.NgAuthRoutingModule,
          i1.NgAuthRoutingModule,([] as any[])),i0.ɵmpd(1024,i5.ROUTES,() => {
        return [[{path:'ngauth',component:i6.NgAuthComponent,children:[{path:'ngadmin',
            component:i7.NgAuthNgadminComponent},{path:'nguser',component:i8.NgAuthUserComponent},
            {path:'**',pathMatch:'full',redirectTo:'/ngauth/nguser'}]}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0F1dGgvbmctYXV0aC1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQXV0aC9uZy1hdXRoLXJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
