/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-auth.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './Components/ng-auth-nav/ng-auth-nav.component.ngfactory';
import * as i3 from './Components/ng-auth-nav/ng-auth-nav.component';
import * as i4 from '@angular/router';
import * as i5 from './ng-auth.component';
const styles_NgAuthComponent:any[] = [i0.styles];
export const RenderType_NgAuthComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAuthComponent,data:{}});
export function View_NgAuthComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-auth-nav',
      ([] as any[]),(null as any),(null as any),(null as any),i2.View_NgAuthNavComponent_0,
      i2.RenderType_NgAuthNavComponent)),i1.ɵdid(114688,(null as any),0,i3.NgAuthNavComponent,
      ([] as any[]),(null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(212992,(null as any),0,i4.RouterOutlet,[i4.ChildrenOutletContexts,i1.ViewContainerRef,
          i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,1,0);
    _ck(_v,4,0);
  },(null as any));
}
export function View_NgAuthComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-auth',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAuthComponent_0,
      RenderType_NgAuthComponent)),i1.ɵdid(114688,(null as any),0,i5.NgAuthComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NgAuthComponentNgFactory:i1.ComponentFactory<i5.NgAuthComponent> = i1.ɵccf('app-ng-auth',
    i5.NgAuthComponent,View_NgAuthComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0F1dGgvbmctYXV0aC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0F1dGgvbmctYXV0aC5jb21wb25lbnQudHMiLCJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQXV0aC9uZy1hdXRoLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0F1dGgvbmctYXV0aC5jb21wb25lbnQudHMuTmdBdXRoQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFwcC1uZy1hdXRoLW5hdj48L2FwcC1uZy1hdXRoLW5hdj5cbjxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cbiIsIjxhcHAtbmctYXV0aD48L2FwcC1uZy1hdXRoPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO3NDQUFBLFVBQUE7TUFBQSwyQ0FBbUM7TUFDbkM7VUFBQTthQUFBO3NDQUFBO1VBQUEsZUFBK0I7SUFEL0I7SUFDQTs7OztvQkNEQTtNQUFBO2dDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
