/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './home.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from '@angular/common';
import * as i4 from './home.component';
const styles_HomeComponent:any[] = [i0.styles];
export const RenderType_HomeComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_HomeComponent,data:{}});
export function View_HomeComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),16,'ul',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n	'])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),2,'a',[['routerLink','/']],[[1,'target',0],[8,'href',4]],[[(null as any),
          'click']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,5).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(671744,(null as any),0,i2.RouterLinkWithHref,
      [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),(_l()(),i1.ɵted((null as any),['Home'])),(_l()(),i1.ɵted((null as any),
      ['\n	'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),2,'a',[['routerLink','/ngauth']],[[1,'target',
          0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,10).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(671744,(null as any),0,i2.RouterLinkWithHref,
      [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),(_l()(),i1.ɵted((null as any),['Ng Auth'])),(_l()(),i1.ɵted((null as any),
      ['\n	'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),2,'a',[['routerLink','/ngadmin']],[[1,
          'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,15).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(671744,(null as any),0,i2.RouterLinkWithHref,
      [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),(_l()(),i1.ɵted((null as any),['Ng Admin'])),(_l()(),i1.ɵted((null as any),
      ['\n'])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n	Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum cum, possimus dolores commodi quibusdam obcaecati porro ipsa modi quasi iste sequi quas reiciendis aperiam, nisi officiis facere, nesciunt optio odio?\n'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    const currVal_2:any = '/';
    _ck(_v,5,0,currVal_2);
    const currVal_5:any = '/ngauth';
    _ck(_v,10,0,currVal_5);
    const currVal_8:any = '/ngadmin';
    _ck(_v,15,0,currVal_8);
  },(_ck,_v) => {
    const currVal_0:any = i1.ɵnov(_v,5).target;
    const currVal_1:any = i1.ɵnov(_v,5).href;
    _ck(_v,4,0,currVal_0,currVal_1);
    const currVal_3:any = i1.ɵnov(_v,10).target;
    const currVal_4:any = i1.ɵnov(_v,10).href;
    _ck(_v,9,0,currVal_3,currVal_4);
    const currVal_6:any = i1.ɵnov(_v,15).target;
    const currVal_7:any = i1.ɵnov(_v,15).href;
    _ck(_v,14,0,currVal_6,currVal_7);
  });
}
export function View_HomeComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-home',([] as any[]),
      (null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
      i1.ɵdid(114688,(null as any),0,i4.HomeComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const HomeComponentNgFactory:i1.ComponentFactory<i4.HomeComponent> = i1.ɵccf('app-home',
    i4.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvQ29tcG9uZW50cy9ob21lL2hvbWUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL0NvbXBvbmVudHMvaG9tZS9ob21lLmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL0NvbXBvbmVudHMvaG9tZS9ob21lLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvQ29tcG9uZW50cy9ob21lL2hvbWUuY29tcG9uZW50LnRzLkhvbWVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbjx1bD5cblx0PGxpPjxhIHJvdXRlckxpbms9Jy8nPkhvbWU8L2E+PC9saT5cblx0PGxpPjxhIHJvdXRlckxpbms9Jy9uZ2F1dGgnPk5nIEF1dGg8L2E+PC9saT5cblx0PGxpPjxhIHJvdXRlckxpbms9Jy9uZ2FkbWluJz5OZyBBZG1pbjwvYT48L2xpPlxuPC91bD5cbjxwPlxuXHRMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCBjb25zZWN0ZXR1ciBhZGlwaXNpY2luZyBlbGl0LiBJcHN1bSBjdW0sIHBvc3NpbXVzIGRvbG9yZXMgY29tbW9kaSBxdWlidXNkYW0gb2JjYWVjYXRpIHBvcnJvIGlwc2EgbW9kaSBxdWFzaSBpc3RlIHNlcXVpIHF1YXMgcmVpY2llbmRpcyBhcGVyaWFtLCBuaXNpIG9mZmljaWlzIGZhY2VyZSwgbmVzY2l1bnQgb3B0aW8gb2Rpbz9cbjwvcD5cbiIsIjxhcHAtaG9tZT48L2FwcC1ob21lPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLHVDQUNBO01BQUE7TUFBQSw4QkFBSSx3Q0FDSDthQUFBO1VBQUEsNENBQUk7TUFBQTtVQUFBO1FBQUE7UUFBQTtVQUFBO2NBQUE7VUFBQTtRQUFBO1FBQUE7TUFBQSx1Q0FBQTtNQUFBO01BQUEsZUFBa0IseUNBQWE7TUFBQSxVQUNuQztNQUFBLHdFQUFJO2FBQUE7VUFBQTtRQUFBO1FBQUE7VUFBQTtjQUFBO1VBQUE7UUFBQTtRQUFBO01BQUEsdUNBQUE7TUFBQTtNQUFBLGVBQXdCLDRDQUFnQjtNQUFBLFVBQzVDO01BQUEsd0VBQUk7YUFBQTtVQUFBO1FBQUE7UUFBQTtVQUFBO2NBQUE7VUFBQTtRQUFBO1FBQUE7TUFBQSx1Q0FBQTtNQUFBO01BQUEsZUFBeUIsNkNBQWlCO01BQUEsU0FDMUMsdUNBQ0w7TUFBQTtNQUFBLDhCQUFHO01BRUM7SUFOSTtJQUFILFdBQUcsU0FBSDtJQUNHO0lBQUgsWUFBRyxTQUFIO0lBQ0c7SUFBSCxZQUFHLFNBQUg7O0lBRkE7SUFBQTtJQUFBLFdBQUEsbUJBQUE7SUFDQTtJQUFBO0lBQUEsV0FBQSxtQkFBQTtJQUNBO0lBQUE7SUFBQSxZQUFBLG1CQUFBOzs7O29CQ0pMO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7In0=
