/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin-transaksi-data-table.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './ng-admin-transaksi-data-table.component';
const styles_NgAdminTransaksiDataTableComponent:any[] = [i0.styles];
export const RenderType_NgAdminTransaksiDataTableComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminTransaksiDataTableComponent,data:{}});
export function View_NgAdminTransaksiDataTableComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  ngadmin-transaksi-data-table works!\n'])),(_l()(),
      i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_NgAdminTransaksiDataTableComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-transaksi-data-table',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminTransaksiDataTableComponent_0,
      RenderType_NgAdminTransaksiDataTableComponent)),i1.ɵdid(49152,(null as any),
      0,i2.NgAdminTransaksiDataTableComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const NgAdminTransaksiDataTableComponentNgFactory:i1.ComponentFactory<i2.NgAdminTransaksiDataTableComponent> = i1.ɵccf('app-ng-admin-transaksi-data-table',
    i2.NgAdminTransaksiDataTableComponent,View_NgAdminTransaksiDataTableComponent_Host_0,
    {},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tdHJhbnNha3NpLWRhdGEtdGFibGUvbmctYWRtaW4tdHJhbnNha3NpLWRhdGEtdGFibGUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL01vZHVsZXMvbmdBZG1pbi9Db21wb25lbnRzL25nLWFkbWluLXRyYW5zYWtzaS1kYXRhLXRhYmxlL25nLWFkbWluLXRyYW5zYWtzaS1kYXRhLXRhYmxlLmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL01vZHVsZXMvbmdBZG1pbi9Db21wb25lbnRzL25nLWFkbWluLXRyYW5zYWtzaS1kYXRhLXRhYmxlL25nLWFkbWluLXRyYW5zYWtzaS1kYXRhLXRhYmxlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tdHJhbnNha3NpLWRhdGEtdGFibGUvbmctYWRtaW4tdHJhbnNha3NpLWRhdGEtdGFibGUuY29tcG9uZW50LnRzLk5nQWRtaW5UcmFuc2Frc2lEYXRhVGFibGVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgbmdhZG1pbi10cmFuc2Frc2ktZGF0YS10YWJsZSB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtbmctYWRtaW4tdHJhbnNha3NpLWRhdGEtdGFibGU+PC9hcHAtbmctYWRtaW4tdHJhbnNha3NpLWRhdGEtdGFibGU+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSwrREFFQzthQUFBOzs7b0JDRko7TUFBQTttREFBQSxVQUFBO01BQUE7Ozs7OyJ9
