/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.mat-toolbar[_ngcontent-%COMP%]{\r\n	margin: 0;\r\n	padding: 0;\r\n}\r\n.demo-toolbar[_ngcontent-%COMP%] {\r\n	display: inline;\r\n	margin: 0 !important;\r\n	padding: 0 !important;\r\n	position: fixed;\r\n	top: 0;\r\n	width: 100%;\r\n	z-index: 10000 !important;\r\n	p {\r\n		margin: 0 !important;\r\n	}\r\n	.btn-ngadmin-menu-nav-icon {\r\n		background-color: transparent;\r\n		box-sizing: border-box;\r\n		border: none;\r\n		justify-content: center;\r\n		height: 100%;\r\n		padding-top: .95%;\r\n		width: 64px;\r\n	}\r\n	.btn-ngadmin-menu-nav-icon:hover,\r\n	.btn-ngadmin-menu-nav-icon.active {\r\n		border: 2px solid #90CAF9;\r\n	}\r\n	.company-name{\r\n		margin-left: 20px;\r\n	}\r\n	.demo-toolbar-icon:hover {\r\n		cursor: pointer;\r\n	}\r\n	.demo-fill-remaining {\r\n		flex: 1 1 auto;\r\n	}\r\n}\r\n\r\n@media (max-width: 600px){\r\n	.demo-toolbar[_ngcontent-%COMP%]{\r\n		.btn-ngadmin-menu-nav-icon{\r\n			padding-top: 2%;\r\n			width: 56px;\r\n		}\r\n	}\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tbmF2L25nLWFkbWluLW5hdi5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vQ29tcG9uZW50cy9uZy1hZG1pbi1uYXYvbmctYWRtaW4tbmF2LmNvbXBvbmVudC5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
