/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin-ng-user-data-table.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './ng-admin-ng-user-data-table.component';
const styles_NgAdminNgUserDataTableComponent:any[] = [i0.styles];
export const RenderType_NgAdminNgUserDataTableComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminNgUserDataTableComponent,data:{}});
export function View_NgAdminNgUserDataTableComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  ngadmin-nguser-data-table works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_NgAdminNgUserDataTableComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-ng-user-data-table',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminNgUserDataTableComponent_0,
      RenderType_NgAdminNgUserDataTableComponent)),i1.ɵdid(49152,(null as any),0,i2.NgAdminNgUserDataTableComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NgAdminNgUserDataTableComponentNgFactory:i1.ComponentFactory<i2.NgAdminNgUserDataTableComponent> = i1.ɵccf('app-ng-admin-ng-user-data-table',
    i2.NgAdminNgUserDataTableComponent,View_NgAdminNgUserDataTableComponent_Host_0,
    {},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tbmctdXNlci1kYXRhLXRhYmxlL25nLWFkbWluLW5nLXVzZXItZGF0YS10YWJsZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tbmctdXNlci1kYXRhLXRhYmxlL25nLWFkbWluLW5nLXVzZXItZGF0YS10YWJsZS5jb21wb25lbnQudHMiLCJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vQ29tcG9uZW50cy9uZy1hZG1pbi1uZy11c2VyLWRhdGEtdGFibGUvbmctYWRtaW4tbmctdXNlci1kYXRhLXRhYmxlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tbmctdXNlci1kYXRhLXRhYmxlL25nLWFkbWluLW5nLXVzZXItZGF0YS10YWJsZS5jb21wb25lbnQudHMuTmdBZG1pbk5nVXNlckRhdGFUYWJsZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICBuZ2FkbWluLW5ndXNlci1kYXRhLXRhYmxlIHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1uZy1hZG1pbi1uZy11c2VyLWRhdGEtdGFibGU+PC9hcHAtbmctYWRtaW4tbmctdXNlci1kYXRhLXRhYmxlPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFHO2FBQUEsNERBRUM7TUFBQTs7O29CQ0ZKO01BQUE7Z0RBQUEsVUFBQTtNQUFBOzs7OyJ9
