/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin-home.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './ng-admin-home.component';
const styles_NgAdminHomeComponent:any[] = [i0.styles];
export const RenderType_NgAdminHomeComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminHomeComponent,data:{}});
export function View_NgAdminHomeComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  ngadmin-home works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_NgAdminHomeComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-home',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminHomeComponent_0,
      RenderType_NgAdminHomeComponent)),i1.ɵdid(49152,(null as any),0,i2.NgAdminHomeComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NgAdminHomeComponentNgFactory:i1.ComponentFactory<i2.NgAdminHomeComponent> = i1.ɵccf('app-ng-admin-home',
    i2.NgAdminHomeComponent,View_NgAdminHomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4taG9tZS9uZy1hZG1pbi1ob21lLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vQ29tcG9uZW50cy9uZy1hZG1pbi1ob21lL25nLWFkbWluLWhvbWUuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4taG9tZS9uZy1hZG1pbi1ob21lLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4taG9tZS9uZy1hZG1pbi1ob21lLmNvbXBvbmVudC50cy5OZ0FkbWluSG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICBuZ2FkbWluLWhvbWUgd29ya3MhXG48L3A+XG4iLCI8YXBwLW5nLWFkbWluLWhvbWU+PC9hcHAtbmctYWRtaW4taG9tZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLCtDQUVDO01BQUE7OztvQkNGSjtNQUFBO3FDQUFBLFVBQUE7TUFBQTs7OyJ9
