/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin-kategori.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../ng-admin-kategori-form/ng-admin-kategori-form.component.ngfactory';
import * as i3 from '../ng-admin-kategori-form/ng-admin-kategori-form.component';
import * as i4 from '@angular/forms';
import * as i5 from '@angular/router';
import * as i6 from '../../../../Services/form/form.service';
import * as i7 from '../ng-admin-kategori-data-table/ng-admin-kategori-data-table.component.ngfactory';
import * as i8 from '../ng-admin-kategori-data-table/ng-admin-kategori-data-table.component';
import * as i9 from './ng-admin-kategori.component';
const styles_NgAdminKategoriComponent:any[] = [i0.styles];
export const RenderType_NgAdminKategoriComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminKategoriComponent,data:{}});
export function View_NgAdminKategoriComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-kategori-form',
      ([] as any[]),(null as any),(null as any),(null as any),i2.View_NgAdminKategoriFormComponent_0,
      i2.RenderType_NgAdminKategoriFormComponent)),i1.ɵdid(114688,(null as any),0,
      i3.NgAdminKategoriFormComponent,[i4.FormBuilder,i5.Router,i6.FormService],(null as any),
      (null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),1,'app-ng-admin-kategori-data-table',([] as any[]),(null as any),
      (null as any),(null as any),i7.View_NgAdminKategoriDataTableComponent_0,i7.RenderType_NgAdminKategoriDataTableComponent)),
      i1.ɵdid(49152,(null as any),0,i8.NgAdminKategoriDataTableComponent,([] as any[]),
          (null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,
      _v) => {
    _ck(_v,1,0);
  },(null as any));
}
export function View_NgAdminKategoriComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-kategori',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminKategoriComponent_0,
      RenderType_NgAdminKategoriComponent)),i1.ɵdid(49152,(null as any),0,i9.NgAdminKategoriComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NgAdminKategoriComponentNgFactory:i1.ComponentFactory<i9.NgAdminKategoriComponent> = i1.ɵccf('app-ng-admin-kategori',
    i9.NgAdminKategoriComponent,View_NgAdminKategoriComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4ta2F0ZWdvcmkvbmctYWRtaW4ta2F0ZWdvcmkuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL01vZHVsZXMvbmdBZG1pbi9Db21wb25lbnRzL25nLWFkbWluLWthdGVnb3JpL25nLWFkbWluLWthdGVnb3JpLmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL01vZHVsZXMvbmdBZG1pbi9Db21wb25lbnRzL25nLWFkbWluLWthdGVnb3JpL25nLWFkbWluLWthdGVnb3JpLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4ta2F0ZWdvcmkvbmctYWRtaW4ta2F0ZWdvcmkuY29tcG9uZW50LnRzLk5nQWRtaW5LYXRlZ29yaUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxhcHAtbmctYWRtaW4ta2F0ZWdvcmktZm9ybT48L2FwcC1uZy1hZG1pbi1rYXRlZ29yaS1mb3JtPlxuPGFwcC1uZy1hZG1pbi1rYXRlZ29yaS1kYXRhLXRhYmxlPjwvYXBwLW5nLWFkbWluLWthdGVnb3JpLWRhdGEtdGFibGU+XG4iLCI8YXBwLW5nLWFkbWluLWthdGVnb3JpPjwvYXBwLW5nLWFkbWluLWthdGVnb3JpPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtnREFBQSxVQUFBO3NDQUFBO01BQUEsZUFBeUQsdUNBQ3pEO01BQUE7TUFBQTthQUFBO1VBQUEsNkJBQXFFOztJQURyRTs7OztvQkNBQTtNQUFBO3lDQUFBLFVBQUE7TUFBQTs7OyJ9
