/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app-routing.module';
import * as i2 from './Modules/ngAuth/ng-auth.component.ngfactory';
import * as i3 from './Modules/ngAuth/Components/ng-auth-ngadmin/ng-auth-ngadmin.component.ngfactory';
import * as i4 from './Modules/ngAuth/Components/ng-auth-user/ng-auth-user.component.ngfactory';
import * as i5 from './Modules/ngAdmin/ng-admin.component.ngfactory';
import * as i6 from './Modules/ngAdmin/Components/ng-admin-home/ng-admin-home.component.ngfactory';
import * as i7 from './Modules/ngAdmin/Components/ng-admin-ng-user/ng-admin-ng-user.component.ngfactory';
import * as i8 from './Modules/ngAdmin/Components/ng-admin-kategori/ng-admin-kategori.component.ngfactory';
import * as i9 from './Modules/ngAdmin/Components/ng-admin-barang/ng-admin-barang.component.ngfactory';
import * as i10 from './Modules/ngAdmin/Components/ng-admin-transaksi/ng-admin-transaksi.component.ngfactory';
import * as i11 from './Modules/ngAdmin/Components/ng-admin-testimoni/ng-admin-testimoni.component.ngfactory';
import * as i12 from './Components/home/home.component.ngfactory';
import * as i13 from '@angular/router';
import * as i14 from '@angular/common';
import * as i15 from './Modules/ngAuth/ng-auth.component';
import * as i16 from './Modules/ngAuth/Components/ng-auth-ngadmin/ng-auth-ngadmin.component';
import * as i17 from './Modules/ngAuth/Components/ng-auth-user/ng-auth-user.component';
import * as i18 from './Modules/ngAdmin/ng-admin.component';
import * as i19 from './Modules/ngAdmin/Guards/ngadmin-children/ngadmin-children.guard';
import * as i20 from './Modules/ngAdmin/Components/ng-admin-home/ng-admin-home.component';
import * as i21 from './Modules/ngAdmin/Components/ng-admin-ng-user/ng-admin-ng-user.component';
import * as i22 from './Modules/ngAdmin/Components/ng-admin-kategori/ng-admin-kategori.component';
import * as i23 from './Modules/ngAdmin/Components/ng-admin-barang/ng-admin-barang.component';
import * as i24 from './Modules/ngAdmin/Components/ng-admin-transaksi/ng-admin-transaksi.component';
import * as i25 from './Modules/ngAdmin/Components/ng-admin-testimoni/ng-admin-testimoni.component';
import * as i26 from './Components/home/home.component';
import * as i27 from './Modules/ngAuth/ng-auth-routing.module';
import * as i28 from './Modules/ngAdmin/ng-admin-routing.module';
export const AppRoutingModuleNgFactory:i0.NgModuleFactory<i1.AppRoutingModule> = i0.ɵcmf(i1.AppRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.NgAuthComponentNgFactory,i3.NgAuthNgadminComponentNgFactory,i4.NgAuthUserComponentNgFactory,
              i5.NgAdminComponentNgFactory,i6.NgAdminHomeComponentNgFactory,i7.NgAdminNgUserComponentNgFactory,
              i8.NgAdminKategoriComponentNgFactory,i9.NgAdminBarangComponentNgFactory,
              i10.NgAdminTransaksiComponentNgFactory,i11.NgAdminTestimoniComponentNgFactory,
              i12.HomeComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i13.ActivatedRoute,i13.ɵf,[i13.Router]),i0.ɵmpd(4608,i13.NoPreloading,
              i13.NoPreloading,([] as any[])),i0.ɵmpd(6144,i13.PreloadingStrategy,
              (null as any),[i13.NoPreloading]),i0.ɵmpd(135680,i13.RouterPreloader,
              i13.RouterPreloader,[i13.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i13.PreloadingStrategy]),i0.ɵmpd(4608,i13.PreloadAllModules,
              i13.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i0.NgProbeToken,() => {
            return [i13.ɵb()];
          },([] as any[])),i0.ɵmpd(4608,i13.ɵg,i13.ɵg,[i0.Injector]),i0.ɵmpd(5120,
              i0.APP_INITIALIZER,(p0_0:any) => {
                return [i13.ɵh(p0_0)];
              },[i13.ɵg]),i0.ɵmpd(5120,i13.ROUTER_INITIALIZER,i13.ɵi,[i13.ɵg]),i0.ɵmpd(5120,
              i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
                return [p0_0];
              },[i13.ROUTER_INITIALIZER]),i0.ɵmpd(1024,i13.ɵa,i13.ɵd,[[3,i13.Router]]),
          i0.ɵmpd(512,i13.UrlSerializer,i13.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i13.ChildrenOutletContexts,i13.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i13.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i14.LocationStrategy,
              i13.ɵc,[i14.PlatformLocation,[2,i14.APP_BASE_HREF],i13.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i14.Location,i14.Location,[i14.LocationStrategy]),i0.ɵmpd(512,
              i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i13.ROUTES,() => {
            return [[{path:'ngauth',component:i15.NgAuthComponent,children:[{path:'ngadmin',
                component:i16.NgAuthNgadminComponent},{path:'nguser',component:i17.NgAuthUserComponent},
                {path:'**',pathMatch:'full',redirectTo:'/ngauth/nguser'}]}],[{path:'ngadmin',
                component:i18.NgAdminComponent,canActivateChild:[i19.NgadminChildrenGuard],
                children:[{path:'dashboard',component:i20.NgAdminHomeComponent},{path:'users',
                    component:i21.NgAdminNgUserComponent},{path:'kategori',component:i22.NgAdminKategoriComponent},
                    {path:'barang',component:i23.NgAdminBarangComponent},{path:'transaksi',
                        component:i24.NgAdminTransaksiComponent},{path:'testimoni',
                        component:i25.NgAdminTestimoniComponent},{path:'**',pathMatch:'full',
                        redirectTo:'/ngadmin/dashboard'}]}],[{path:'',component:i26.HomeComponent},
                {path:'**',pathMatch:'full',redirectTo:'/'}]];
          },([] as any[])),i0.ɵmpd(1024,i13.Router,i13.ɵe,[i0.ApplicationRef,i13.UrlSerializer,
              i13.ChildrenOutletContexts,i14.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i13.ROUTES,i13.ROUTER_CONFIGURATION,[2,i13.UrlHandlingStrategy],
              [2,i13.RouteReuseStrategy]]),i0.ɵmpd(512,i13.RouterModule,i13.RouterModule,
              [[2,i13.ɵa],[2,i13.Router]]),i0.ɵmpd(512,i27.NgAuthRoutingModule,i27.NgAuthRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i28.NgAdminRoutingModule,i28.NgAdminRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppRoutingModule,i1.AppRoutingModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvYXBwLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL2FwcC1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
