/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './Modules/ngAuth/ng-auth.component.ngfactory';
import * as i4 from './Modules/ngAuth/Components/ng-auth-ngadmin/ng-auth-ngadmin.component.ngfactory';
import * as i5 from './Modules/ngAuth/Components/ng-auth-user/ng-auth-user.component.ngfactory';
import * as i6 from './Modules/ngAdmin/ng-admin.component.ngfactory';
import * as i7 from './Modules/ngAdmin/Components/ng-admin-home/ng-admin-home.component.ngfactory';
import * as i8 from './Modules/ngAdmin/Components/ng-admin-ng-user/ng-admin-ng-user.component.ngfactory';
import * as i9 from './Modules/ngAdmin/Components/ng-admin-kategori/ng-admin-kategori.component.ngfactory';
import * as i10 from './Modules/ngAdmin/Components/ng-admin-barang/ng-admin-barang.component.ngfactory';
import * as i11 from './Modules/ngAdmin/Components/ng-admin-transaksi/ng-admin-transaksi.component.ngfactory';
import * as i12 from './Modules/ngAdmin/Components/ng-admin-testimoni/ng-admin-testimoni.component.ngfactory';
import * as i13 from './Components/home/home.component.ngfactory';
import * as i14 from '../../node_modules/@angular/material/typings/index.ngfactory';
import * as i15 from './app.component.ngfactory';
import * as i16 from '@angular/router';
import * as i17 from '@angular/common';
import * as i18 from '@angular/platform-browser';
import * as i19 from '@angular/material';
import * as i20 from '@angular/animations/browser';
import * as i21 from '@angular/platform-browser/animations';
import * as i22 from '@angular/animations';
import * as i23 from '@angular/flex-layout/media-query/breakpoints/break-points-token';
import * as i24 from '@angular/flex-layout/media-query/breakpoints/break-points-provider';
import * as i25 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as i26 from '@angular/flex-layout/media-query/match-media';
import * as i27 from '@angular/flex-layout/media-query/media-monitor';
import * as i28 from '@angular/flex-layout/media-query/media-monitor-provider';
import * as i29 from '@angular/flex-layout/media-query/observable-media';
import * as i30 from '@angular/flex-layout/media-query/observable-media-provider';
import * as i31 from '@angular/forms';
import * as i32 from '@angular/http';
import * as i33 from './Services/form/form.service';
import * as i34 from './Modules/ngAdmin/Guards/ngadmin-children/ngadmin-children.guard';
import * as i35 from './Modules/ngAuth/ng-auth.component';
import * as i36 from './Modules/ngAuth/Components/ng-auth-ngadmin/ng-auth-ngadmin.component';
import * as i37 from './Modules/ngAuth/Components/ng-auth-user/ng-auth-user.component';
import * as i38 from './Modules/ngAdmin/ng-admin.component';
import * as i39 from './Modules/ngAdmin/Components/ng-admin-home/ng-admin-home.component';
import * as i40 from './Modules/ngAdmin/Components/ng-admin-ng-user/ng-admin-ng-user.component';
import * as i41 from './Modules/ngAdmin/Components/ng-admin-kategori/ng-admin-kategori.component';
import * as i42 from './Modules/ngAdmin/Components/ng-admin-barang/ng-admin-barang.component';
import * as i43 from './Modules/ngAdmin/Components/ng-admin-transaksi/ng-admin-transaksi.component';
import * as i44 from './Modules/ngAdmin/Components/ng-admin-testimoni/ng-admin-testimoni.component';
import * as i45 from './Components/home/home.component';
import * as i46 from './Modules/ngAuth/ng-auth-routing.module';
import * as i47 from './Modules/ngAdmin/ng-admin-routing.module';
import * as i48 from './app-routing.module';
import * as i49 from '@angular/flex-layout/media-query/_module';
import * as i50 from '@angular/flex-layout/flexbox/_module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.NgAuthComponentNgFactory,i4.NgAuthNgadminComponentNgFactory,i5.NgAuthUserComponentNgFactory,
              i6.NgAdminComponentNgFactory,i7.NgAdminHomeComponentNgFactory,i8.NgAdminNgUserComponentNgFactory,
              i9.NgAdminKategoriComponentNgFactory,i10.NgAdminBarangComponentNgFactory,
              i11.NgAdminTransaksiComponentNgFactory,i12.NgAdminTestimoniComponentNgFactory,
              i13.HomeComponentNgFactory,i14.MdDialogContainerNgFactory,i14.MdDatepickerContentNgFactory,
              i14.TooltipComponentNgFactory,i14.MdSnackBarContainerNgFactory,i14.SimpleSnackBarNgFactory,
              i15.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i16.ActivatedRoute,i16.ɵf,[i16.Router]),i0.ɵmpd(4608,i16.NoPreloading,
              i16.NoPreloading,([] as any[])),i0.ɵmpd(6144,i16.PreloadingStrategy,
              (null as any),[i16.NoPreloading]),i0.ɵmpd(135680,i16.RouterPreloader,
              i16.RouterPreloader,[i16.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i16.PreloadingStrategy]),i0.ɵmpd(4608,i16.PreloadAllModules,
              i16.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i16.ROUTER_INITIALIZER,
              i16.ɵi,[i16.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i16.ROUTER_INITIALIZER]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i17.NgLocalization,i17.NgLocaleLocalization,[i0.LOCALE_ID]),
          i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,
              i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i18.DomSanitizer,i18.ɵe,[i18.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i18.DomSanitizer]),i0.ɵmpd(4608,i18.HAMMER_GESTURE_CONFIG,
              i19.GestureConfig,([] as any[])),i0.ɵmpd(5120,i18.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i18.ɵDomEventsPlugin(p0_0),new i18.ɵKeyEventsPlugin(p1_0),
                    new i18.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i18.DOCUMENT,i18.DOCUMENT,i18.DOCUMENT,i18.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i18.EventManager,i18.EventManager,[i18.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i18.ɵDomSharedStylesHost,i18.ɵDomSharedStylesHost,
              [i18.DOCUMENT]),i0.ɵmpd(4608,i18.ɵDomRendererFactory2,i18.ɵDomRendererFactory2,
              [i18.EventManager,i18.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i20.AnimationDriver,
              i20.ɵNoopAnimationDriver,([] as any[])),i0.ɵmpd(5120,i20.ɵAnimationStyleNormalizer,
              i21.ɵd,([] as any[])),i0.ɵmpd(4608,i20.ɵAnimationEngine,i21.ɵb,[i20.AnimationDriver,
              i20.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i21.ɵe,
              [i18.ɵDomRendererFactory2,i20.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i18.ɵSharedStylesHost,(null as any),[i18.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i18.Meta,i18.Meta,
              [i18.DOCUMENT]),i0.ɵmpd(4608,i18.Title,i18.Title,[i18.DOCUMENT]),i0.ɵmpd(4608,
              i22.AnimationBuilder,i21.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(5120,i23.BREAKPOINTS,i24.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY,([] as any[])),
          i0.ɵmpd(4608,i25.BreakPointRegistry,i25.BreakPointRegistry,[i23.BREAKPOINTS]),
          i0.ɵmpd(4608,i26.MatchMedia,i26.MatchMedia,[i0.NgZone]),i0.ɵmpd(5120,i27.MediaMonitor,
              i28.MEDIA_MONITOR_PROVIDER_FACTORY,[[3,i27.MediaMonitor],i25.BreakPointRegistry,
                  i26.MatchMedia]),i0.ɵmpd(5120,i29.ObservableMedia,i30.OBSERVABLE_MEDIA_PROVIDER_FACTORY,
              [[3,i29.ObservableMedia],i26.MatchMedia,i25.BreakPointRegistry]),i0.ɵmpd(4608,
              i31.ɵi,i31.ɵi,([] as any[])),i0.ɵmpd(6144,i19.ɵa,(null as any),[i18.DOCUMENT]),
          i0.ɵmpd(4608,i19.Directionality,i19.Directionality,[[2,i19.ɵa]]),i0.ɵmpd(4608,
              i19.Platform,i19.Platform,([] as any[])),i0.ɵmpd(5120,i19.ScrollDispatcher,
              i19.ɵg,[[3,i19.ScrollDispatcher],i0.NgZone,i19.Platform]),i0.ɵmpd(5120,
              i19.ViewportRuler,i19.ɵe,[[3,i19.ViewportRuler],i19.ScrollDispatcher]),
          i0.ɵmpd(4608,i19.ScrollStrategyOptions,i19.ScrollStrategyOptions,[i19.ScrollDispatcher,
              i19.ViewportRuler]),i0.ɵmpd(5120,i19.OverlayContainer,i19.ɵc,[[3,i19.OverlayContainer]]),
          i0.ɵmpd(4608,i19.ɵw,i19.ɵw,[i19.ViewportRuler]),i0.ɵmpd(4608,i19.Overlay,
              i19.Overlay,[i19.ScrollStrategyOptions,i19.OverlayContainer,i0.ComponentFactoryResolver,
                  i19.ɵw,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i19.FocusOriginMonitor,
              i19.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,[[3,i19.FocusOriginMonitor],
                  i0.NgZone,i19.Platform]),i0.ɵmpd(5120,i19.UniqueSelectionDispatcher,
              i19.ɵk,[[3,i19.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i19.ɵb,i19.ɵb,
              ([] as any[])),i0.ɵmpd(4608,i19.InteractivityChecker,i19.InteractivityChecker,
              [i19.Platform]),i0.ɵmpd(4608,i19.FocusTrapFactory,i19.FocusTrapFactory,
              [i19.InteractivityChecker,i19.Platform,i0.NgZone]),i0.ɵmpd(5120,i19.LiveAnnouncer,
              i19.ɵj,[[3,i19.LiveAnnouncer],[2,i19.LIVE_ANNOUNCER_ELEMENT_TOKEN],i19.Platform]),
          i0.ɵmpd(4608,i19.MdDialog,i19.MdDialog,[i19.Overlay,i0.Injector,[2,i17.Location],
              [3,i19.MdDialog]]),i0.ɵmpd(4608,i19.MdDatepickerIntl,i19.MdDatepickerIntl,
              ([] as any[])),i0.ɵmpd(5120,i19.MdIconRegistry,i19.ICON_REGISTRY_PROVIDER_FACTORY,
              [[3,i19.MdIconRegistry],[2,i32.Http],i18.DomSanitizer]),i0.ɵmpd(4608,
              i19.ɵba,i19.ɵba,([] as any[])),i0.ɵmpd(4608,i19.MdSnackBar,i19.MdSnackBar,
              [i19.Overlay,i19.LiveAnnouncer,[3,i19.MdSnackBar]]),i0.ɵmpd(4608,i19.MdSortHeaderIntl,
              i19.MdSortHeaderIntl,([] as any[])),i0.ɵmpd(4608,i31.FormBuilder,i31.FormBuilder,
              ([] as any[])),i0.ɵmpd(4608,i33.FormService,i33.FormService,([] as any[])),
          i0.ɵmpd(4608,i34.NgadminChildrenGuard,i34.NgadminChildrenGuard,[i16.Router]),
          i0.ɵmpd(1024,i16.ɵa,i16.ɵd,[[3,i16.Router]]),i0.ɵmpd(1024,i0.ErrorHandler,
              i18.ɵa,([] as any[])),i0.ɵmpd(512,i16.ɵg,i16.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i16.ɵb()];
              },([] as any[])),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p1_0:any,
              p1_1:any) => {
            return [i16.ɵh(p0_0),i18.ɵc(p1_0,p1_1)];
          },[i16.ɵg,[2,i18.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i16.UrlSerializer,i16.DefaultUrlSerializer,([] as any[])),
          i0.ɵmpd(512,i16.ChildrenOutletContexts,i16.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i16.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i17.LocationStrategy,
              i16.ɵc,[i17.PlatformLocation,[2,i17.APP_BASE_HREF],i16.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i17.Location,i17.Location,[i17.LocationStrategy]),i0.ɵmpd(512,
              i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i16.ROUTES,() => {
            return [[{path:'ngauth',component:i35.NgAuthComponent,children:[{path:'ngadmin',
                component:i36.NgAuthNgadminComponent},{path:'nguser',component:i37.NgAuthUserComponent},
                {path:'**',pathMatch:'full',redirectTo:'/ngauth/nguser'}]}],[{path:'ngadmin',
                component:i38.NgAdminComponent,canActivateChild:[i34.NgadminChildrenGuard],
                children:[{path:'dashboard',component:i39.NgAdminHomeComponent},{path:'users',
                    component:i40.NgAdminNgUserComponent},{path:'kategori',component:i41.NgAdminKategoriComponent},
                    {path:'barang',component:i42.NgAdminBarangComponent},{path:'transaksi',
                        component:i43.NgAdminTransaksiComponent},{path:'testimoni',
                        component:i44.NgAdminTestimoniComponent},{path:'**',pathMatch:'full',
                        redirectTo:'/ngadmin/dashboard'}]}],[{path:'',component:i45.HomeComponent},
                {path:'**',pathMatch:'full',redirectTo:'/'}]];
          },([] as any[])),i0.ɵmpd(1024,i16.Router,i16.ɵe,[i0.ApplicationRef,i16.UrlSerializer,
              i16.ChildrenOutletContexts,i17.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i16.ROUTES,i16.ROUTER_CONFIGURATION,[2,i16.UrlHandlingStrategy],
              [2,i16.RouteReuseStrategy]]),i0.ɵmpd(512,i16.RouterModule,i16.RouterModule,
              [[2,i16.ɵa],[2,i16.Router]]),i0.ɵmpd(512,i46.NgAuthRoutingModule,i46.NgAuthRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i47.NgAdminRoutingModule,i47.NgAdminRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i48.AppRoutingModule,i48.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i17.CommonModule,i17.CommonModule,([] as any[])),
          i0.ɵmpd(512,i19.CdkDataTableModule,i19.CdkDataTableModule,([] as any[])),
          i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i18.BrowserModule,i18.BrowserModule,[[3,i18.BrowserModule]]),
          i0.ɵmpd(512,i21.BrowserAnimationsModule,i21.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i49.MediaQueriesModule,i49.MediaQueriesModule,([] as any[])),
          i0.ɵmpd(512,i50.FlexLayoutModule,i50.FlexLayoutModule,([] as any[])),i0.ɵmpd(512,
              i31.ɵba,i31.ɵba,([] as any[])),i0.ɵmpd(512,i31.FormsModule,i31.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i19.CompatibilityModule,i19.CompatibilityModule,
              ([] as any[])),i0.ɵmpd(512,i19.BidiModule,i19.BidiModule,([] as any[])),
          i0.ɵmpd(256,i19.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i19.MdCommonModule,
              i19.MdCommonModule,[[2,i18.DOCUMENT],[2,i19.MATERIAL_SANITY_CHECKS]]),
          i0.ɵmpd(512,i19.PlatformModule,i19.PlatformModule,([] as any[])),i0.ɵmpd(512,
              i19.ScrollDispatchModule,i19.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,
              i19.MdRippleModule,i19.MdRippleModule,([] as any[])),i0.ɵmpd(512,i19.MdSelectionModule,
              i19.MdSelectionModule,([] as any[])),i0.ɵmpd(512,i19.MdOptionModule,
              i19.MdOptionModule,([] as any[])),i0.ɵmpd(512,i19.PortalModule,i19.PortalModule,
              ([] as any[])),i0.ɵmpd(512,i19.OverlayModule,i19.OverlayModule,([] as any[])),
          i0.ɵmpd(512,i19.MdAutocompleteModule,i19.MdAutocompleteModule,([] as any[])),
          i0.ɵmpd(512,i19.StyleModule,i19.StyleModule,([] as any[])),i0.ɵmpd(512,i19.MdButtonModule,
              i19.MdButtonModule,([] as any[])),i0.ɵmpd(512,i19.MdButtonToggleModule,
              i19.MdButtonToggleModule,([] as any[])),i0.ɵmpd(512,i19.MdCardModule,
              i19.MdCardModule,([] as any[])),i0.ɵmpd(512,i19.MdChipsModule,i19.MdChipsModule,
              ([] as any[])),i0.ɵmpd(512,i19.ObserveContentModule,i19.ObserveContentModule,
              ([] as any[])),i0.ɵmpd(512,i19.MdCheckboxModule,i19.MdCheckboxModule,
              ([] as any[])),i0.ɵmpd(512,i19.A11yModule,i19.A11yModule,([] as any[])),
          i0.ɵmpd(512,i19.MdDialogModule,i19.MdDialogModule,([] as any[])),i0.ɵmpd(512,
              i19.MdDatepickerModule,i19.MdDatepickerModule,([] as any[])),i0.ɵmpd(512,
              i19.MdExpansionModule,i19.MdExpansionModule,([] as any[])),i0.ɵmpd(512,
              i19.MdLineModule,i19.MdLineModule,([] as any[])),i0.ɵmpd(512,i19.MdGridListModule,
              i19.MdGridListModule,([] as any[])),i0.ɵmpd(512,i19.MdIconModule,i19.MdIconModule,
              ([] as any[])),i0.ɵmpd(512,i19.MdInputModule,i19.MdInputModule,([] as any[])),
          i0.ɵmpd(512,i19.MdListModule,i19.MdListModule,([] as any[])),i0.ɵmpd(512,
              i19.MdMenuModule,i19.MdMenuModule,([] as any[])),i0.ɵmpd(512,i19.MdSelectModule,
              i19.MdSelectModule,([] as any[])),i0.ɵmpd(512,i19.MdTooltipModule,i19.MdTooltipModule,
              ([] as any[])),i0.ɵmpd(512,i19.MdPaginatorModule,i19.MdPaginatorModule,
              ([] as any[])),i0.ɵmpd(512,i19.MdProgressBarModule,i19.MdProgressBarModule,
              ([] as any[])),i0.ɵmpd(512,i19.MdProgressSpinnerModule,i19.MdProgressSpinnerModule,
              ([] as any[])),i0.ɵmpd(512,i19.MdRadioModule,i19.MdRadioModule,([] as any[])),
          i0.ɵmpd(512,i19.MdSidenavModule,i19.MdSidenavModule,([] as any[])),i0.ɵmpd(512,
              i19.MdSliderModule,i19.MdSliderModule,([] as any[])),i0.ɵmpd(512,i19.MdSlideToggleModule,
              i19.MdSlideToggleModule,([] as any[])),i0.ɵmpd(512,i19.MdSnackBarModule,
              i19.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,i19.MdSortModule,i19.MdSortModule,
              ([] as any[])),i0.ɵmpd(512,i19.MdTabsModule,i19.MdTabsModule,([] as any[])),
          i0.ɵmpd(512,i19.MdToolbarModule,i19.MdToolbarModule,([] as any[])),i0.ɵmpd(512,
              i19.MaterialModule,i19.MaterialModule,([] as any[])),i0.ɵmpd(512,i21.NoopAnimationsModule,
              i21.NoopAnimationsModule,([] as any[])),i0.ɵmpd(512,i31.ReactiveFormsModule,
              i31.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
