/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin-sidenav.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i3 from '@angular/router';
import * as i4 from '@angular/common';
import * as i5 from '@angular/material';
import * as i6 from '@angular/flex-layout/flexbox/api/class';
import * as i7 from '@angular/flex-layout/media-query/media-monitor';
import * as i8 from './ng-admin-sidenav.component';
const styles_NgAdminSidenavComponent:any[] = [i0.styles];
export const RenderType_NgAdminSidenavComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminSidenavComponent,data:{}});
function View_NgAdminSidenavComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),5,'a',[['class',
      'mat-list-item'],['md-list-item',''],['role','listitem']],[[1,'target',0],[8,
      'href',4]],[[(null as any),'click'],[(null as any),'focus'],[(null as any),'blur']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,1).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        if (('focus' === en)) {
          const pd_1:any = ((<any>i1.ɵnov(_v,2)._handleFocus()) !== false);
          ad = (pd_1 && ad);
        }
        if (('blur' === en)) {
          const pd_2:any = ((<any>i1.ɵnov(_v,2)._handleBlur()) !== false);
          ad = (pd_2 && ad);
        }
        if (('click' === en)) {
          const pd_3:any = ((<any>_co.$ngadminSidenav$.next()) !== false);
          ad = (pd_3 && ad);
        }
        return ad;
      },i2.View_MdListItem_0,i2.RenderType_MdListItem)),i1.ɵdid(671744,(null as any),
      0,i3.RouterLinkWithHref,[i3.Router,i3.ActivatedRoute,i4.LocationStrategy],{routerLink:[0,
          'routerLink']},(null as any)),i1.ɵdid(1097728,(null as any),2,i5.MdListItem,
      [i1.Renderer2,i1.ElementRef,[2,i5.MdList],[2,i5.MdNavListCssMatStyler]],(null as any),
      (null as any)),i1.ɵqud(603979776,1,{_lines:1}),i1.ɵqud(335544320,2,{_hasAvatar:0}),
      (_l()(),i1.ɵted(2,['\n		','\n	']))],(_ck,_v) => {
    const currVal_2:any = _v.context.$implicit.route;
    _ck(_v,1,0,currVal_2);
  },(_ck,_v) => {
    const currVal_0:any = i1.ɵnov(_v,1).target;
    const currVal_1:any = i1.ɵnov(_v,1).href;
    _ck(_v,0,0,currVal_0,currVal_1);
    const currVal_3:any = _v.context.$implicit.text;
    _ck(_v,5,0,currVal_3);
  });
}
export function View_NgAdminSidenavComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),14,'md-nav-list',
      [['class','abcdef mat-nav-list'],['dense',''],['role','list']],(null as any),
      (null as any),(null as any),i2.View_MdList_0,i2.RenderType_MdList)),i1.ɵdid(933888,
      (null as any),0,i6.ClassDirective,[i7.MediaMonitor,i1.IterableDiffers,i1.KeyValueDiffers,
          i1.ElementRef,i1.Renderer,i1.Renderer2],{classBase:[0,'classBase']},(null as any)),
      i1.ɵdid(16384,(null as any),0,i5.MdPrefixRejector,[[2,i5.MATERIAL_COMPATIBILITY_MODE],
          i1.ElementRef],(null as any),(null as any)),i1.ɵdid(49152,(null as any),
          0,i5.MdList,([] as any[]),(null as any),(null as any)),i1.ɵdid(16384,(null as any),
          0,i5.MdNavListCssMatStyler,([] as any[]),(null as any),(null as any)),(_l()(),
          i1.ɵted(0,['\n	'])),(_l()(),i1.ɵand(16777216,(null as any),0,1,(null as any),
          View_NgAdminSidenavComponent_1)),i1.ɵdid(802816,(null as any),0,i4.NgForOf,
          [i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,'ngForOf']},
          (null as any)),(_l()(),i1.ɵted(0,['\n	'])),(_l()(),i1.ɵeld(0,(null as any),
          0,4,'a',[['class','mat-list-item'],['md-list-item',''],['role','listitem']],
          (null as any),[[(null as any),'focus'],[(null as any),'blur']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('focus' === en)) {
              const pd_0:any = ((<any>i1.ɵnov(_v,10)._handleFocus()) !== false);
              ad = (pd_0 && ad);
            }
            if (('blur' === en)) {
              const pd_1:any = ((<any>i1.ɵnov(_v,10)._handleBlur()) !== false);
              ad = (pd_1 && ad);
            }
            return ad;
          },i2.View_MdListItem_0,i2.RenderType_MdListItem)),i1.ɵdid(1097728,(null as any),
          2,i5.MdListItem,[i1.Renderer2,i1.ElementRef,[2,i5.MdList],[2,i5.MdNavListCssMatStyler]],
          (null as any),(null as any)),i1.ɵqud(603979776,3,{_lines:1}),i1.ɵqud(335544320,
          4,{_hasAvatar:0}),(_l()(),i1.ɵted(2,[' HAHAHAH '])),(_l()(),i1.ɵted(0,['\n'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i8.NgAdminSidenavComponent = _v.component;
    const currVal_0:any = 'abcdef';
    _ck(_v,1,0,currVal_0);
    const currVal_1:any = _co.items;
    _ck(_v,7,0,currVal_1);
  },(null as any));
}
export function View_NgAdminSidenavComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-sidenav',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminSidenavComponent_0,
      RenderType_NgAdminSidenavComponent)),i1.ɵdid(49152,(null as any),0,i8.NgAdminSidenavComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NgAdminSidenavComponentNgFactory:i1.ComponentFactory<i8.NgAdminSidenavComponent> = i1.ɵccf('app-ng-admin-sidenav',
    i8.NgAdminSidenavComponent,View_NgAdminSidenavComponent_Host_0,{},{$ngadminSidenav$:'$ngadminSidenav$'},
    ([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tc2lkZW5hdi9uZy1hZG1pbi1zaWRlbmF2LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vQ29tcG9uZW50cy9uZy1hZG1pbi1zaWRlbmF2L25nLWFkbWluLXNpZGVuYXYuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tc2lkZW5hdi9uZy1hZG1pbi1zaWRlbmF2LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tc2lkZW5hdi9uZy1hZG1pbi1zaWRlbmF2LmNvbXBvbmVudC50cy5OZ0FkbWluU2lkZW5hdkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxtZC1uYXYtbGlzdCBkZW5zZSBjbGFzcz0nYWJjZGVmJz5cblx0PGEgbWQtbGlzdC1pdGVtICpuZ0Zvcj1cImxldCBpdGVtIG9mIGl0ZW1zXCIgKGNsaWNrKT1cIiRuZ2FkbWluU2lkZW5hdiQubmV4dCgpXCIgW3JvdXRlckxpbmtdPVwiaXRlbS5yb3V0ZVwiPlxuXHRcdHt7IGl0ZW0udGV4dCB9fVxuXHQ8L2E+XG5cdDxhIG1kLWxpc3QtaXRlbT4gSEFIQUhBSCA8L2E+XG48L21kLW5hdi1saXN0PlxuIiwiPGFwcC1uZy1hZG1pbi1zaWRlbmF2PjwvYXBwLW5nLWFkbWluLXNpZGVuYXY+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0NDO01BQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO1VBQUE7Y0FBQTtVQUFBO1FBQUE7UUFBQTtVQUFBO1VBQUE7UUFBQTtRQUFBO1VBQUE7VUFBQTtRQUFBO1FBQTJDO1VBQUE7VUFBQTtRQUFBO1FBQTNDO01BQUEseURBQUE7TUFBQTtVQUFBLHFDQUFBO01BQUE7TUFBQTtNQUF1RztJQUExQjtJQUE3RSxXQUE2RSxTQUE3RTs7SUFBQTtJQUFBO0lBQUEsV0FBQSxtQkFBQTtJQUF1RztJQUFBOzs7O29CQUR4RztNQUFBO01BQUEsMkVBQUE7TUFBQTtnREFBQTthQUFBO3VCQUFBLHNDQUFBO1VBQUEsOERBQUE7VUFBQSxzRUFBa0M7aUJBQUEsYUFDakM7VUFBQSx3Q0FBQTtVQUFBO1VBQUEsZUFFSSw0QkFDSjtVQUFBO1VBQUE7WUFBQTtZQUFBO2NBQUE7Y0FBQTtZQUFBO1lBQUE7Y0FBQTtjQUFBO1lBQUE7WUFBQTtVQUFBLHlEQUFBO1VBQUE7VUFBQTtVQUFBLGtCQUFnQixrQ0FBYTtNQUNoQjs7SUFMSztJQUFuQixXQUFtQixTQUFuQjtJQUNpQjtJQUFoQixXQUFnQixTQUFoQjs7OztvQkNERDtNQUFBO3dDQUFBLFVBQUE7TUFBQTs7OzsifQ==
