/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin-testimoni-data-table.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './ng-admin-testimoni-data-table.component';
const styles_NgAdminTestimoniDataTableComponent:any[] = [i0.styles];
export const RenderType_NgAdminTestimoniDataTableComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminTestimoniDataTableComponent,data:{}});
export function View_NgAdminTestimoniDataTableComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  ngadmin-testimoni-data-table works!\n'])),(_l()(),
      i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_NgAdminTestimoniDataTableComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-testimoni-data-table',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminTestimoniDataTableComponent_0,
      RenderType_NgAdminTestimoniDataTableComponent)),i1.ɵdid(49152,(null as any),
      0,i2.NgAdminTestimoniDataTableComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const NgAdminTestimoniDataTableComponentNgFactory:i1.ComponentFactory<i2.NgAdminTestimoniDataTableComponent> = i1.ɵccf('app-ng-admin-testimoni-data-table',
    i2.NgAdminTestimoniDataTableComponent,View_NgAdminTestimoniDataTableComponent_Host_0,
    {},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tdGVzdGltb25pLWRhdGEtdGFibGUvbmctYWRtaW4tdGVzdGltb25pLWRhdGEtdGFibGUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL01vZHVsZXMvbmdBZG1pbi9Db21wb25lbnRzL25nLWFkbWluLXRlc3RpbW9uaS1kYXRhLXRhYmxlL25nLWFkbWluLXRlc3RpbW9uaS1kYXRhLXRhYmxlLmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL01vZHVsZXMvbmdBZG1pbi9Db21wb25lbnRzL25nLWFkbWluLXRlc3RpbW9uaS1kYXRhLXRhYmxlL25nLWFkbWluLXRlc3RpbW9uaS1kYXRhLXRhYmxlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tdGVzdGltb25pLWRhdGEtdGFibGUvbmctYWRtaW4tdGVzdGltb25pLWRhdGEtdGFibGUuY29tcG9uZW50LnRzLk5nQWRtaW5UZXN0aW1vbmlEYXRhVGFibGVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgbmdhZG1pbi10ZXN0aW1vbmktZGF0YS10YWJsZSB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtbmctYWRtaW4tdGVzdGltb25pLWRhdGEtdGFibGU+PC9hcHAtbmctYWRtaW4tdGVzdGltb25pLWRhdGEtdGFibGU+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSwrREFFQzthQUFBOzs7b0JDRko7TUFBQTttREFBQSxVQUFBO01BQUE7Ozs7OyJ9
