/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin-barang.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../ng-admin-barang-form/ng-admin-barang-form.component.ngfactory';
import * as i3 from '../ng-admin-barang-form/ng-admin-barang-form.component';
import * as i4 from '@angular/forms';
import * as i5 from '../../../../Services/form/form.service';
import * as i6 from '../ng-admin-barang-data-table/ng-admin-barang-data-table.component.ngfactory';
import * as i7 from '../ng-admin-barang-data-table/ng-admin-barang-data-table.component';
import * as i8 from './ng-admin-barang.component';
const styles_NgAdminBarangComponent:any[] = [i0.styles];
export const RenderType_NgAdminBarangComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminBarangComponent,data:{}});
export function View_NgAdminBarangComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-barang-form',
      ([] as any[]),(null as any),(null as any),(null as any),i2.View_NgAdminBarangFormComponent_0,
      i2.RenderType_NgAdminBarangFormComponent)),i1.ɵdid(49152,(null as any),0,i3.NgAdminBarangFormComponent,
      [i4.FormBuilder,i5.FormService],(null as any),(null as any)),(_l()(),i1.ɵted((null as any),
      ['\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-barang-data-table',
      ([] as any[]),(null as any),(null as any),(null as any),i6.View_NgAdminBarangDataTableComponent_0,
      i6.RenderType_NgAdminBarangDataTableComponent)),i1.ɵdid(49152,(null as any),
      0,i7.NgAdminBarangDataTableComponent,([] as any[]),(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_NgAdminBarangComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-barang',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminBarangComponent_0,
      RenderType_NgAdminBarangComponent)),i1.ɵdid(49152,(null as any),0,i8.NgAdminBarangComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NgAdminBarangComponentNgFactory:i1.ComponentFactory<i8.NgAdminBarangComponent> = i1.ɵccf('app-ng-admin-barang',
    i8.NgAdminBarangComponent,View_NgAdminBarangComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tYmFyYW5nL25nLWFkbWluLWJhcmFuZy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tYmFyYW5nL25nLWFkbWluLWJhcmFuZy5jb21wb25lbnQudHMiLCJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vQ29tcG9uZW50cy9uZy1hZG1pbi1iYXJhbmcvbmctYWRtaW4tYmFyYW5nLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tYmFyYW5nL25nLWFkbWluLWJhcmFuZy5jb21wb25lbnQudHMuTmdBZG1pbkJhcmFuZ0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxhcHAtbmctYWRtaW4tYmFyYW5nLWZvcm0+PC9hcHAtbmctYWRtaW4tYmFyYW5nLWZvcm0+XG48YXBwLW5nLWFkbWluLWJhcmFuZy1kYXRhLXRhYmxlPjwvYXBwLW5nLWFkbWluLWJhcmFuZy1kYXRhLXRhYmxlPlxuIiwiPGFwcC1uZy1hZG1pbi1iYXJhbmc+PC9hcHAtbmctYWRtaW4tYmFyYW5nPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBOzhDQUFBLFVBQUE7TUFBQSw2REFBcUQ7TUFBQSxTQUNyRDtNQUFBO21EQUFBLFVBQUE7TUFBQTtNQUFpRTs7O29CQ0RqRTtNQUFBO3VDQUFBLFVBQUE7TUFBQTs7OyJ9
