/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin-testimoni.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './ng-admin-testimoni.component';
const styles_NgAdminTestimoniComponent:any[] = [i0.styles];
export const RenderType_NgAdminTestimoniComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminTestimoniComponent,data:{}});
export function View_NgAdminTestimoniComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  ngadmin-testimoni works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_NgAdminTestimoniComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-testimoni',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminTestimoniComponent_0,
      RenderType_NgAdminTestimoniComponent)),i1.ɵdid(49152,(null as any),0,i2.NgAdminTestimoniComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NgAdminTestimoniComponentNgFactory:i1.ComponentFactory<i2.NgAdminTestimoniComponent> = i1.ɵccf('app-ng-admin-testimoni',
    i2.NgAdminTestimoniComponent,View_NgAdminTestimoniComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tdGVzdGltb25pL25nLWFkbWluLXRlc3RpbW9uaS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tdGVzdGltb25pL25nLWFkbWluLXRlc3RpbW9uaS5jb21wb25lbnQudHMiLCJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vQ29tcG9uZW50cy9uZy1hZG1pbi10ZXN0aW1vbmkvbmctYWRtaW4tdGVzdGltb25pLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tdGVzdGltb25pL25nLWFkbWluLXRlc3RpbW9uaS5jb21wb25lbnQudHMuTmdBZG1pblRlc3RpbW9uaUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICBuZ2FkbWluLXRlc3RpbW9uaSB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtbmctYWRtaW4tdGVzdGltb25pPjwvYXBwLW5nLWFkbWluLXRlc3RpbW9uaT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLG9EQUVDO01BQUE7OztvQkNGSjtNQUFBOzBDQUFBLFVBQUE7TUFBQTs7OyJ9
