/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin-transaksi.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../ng-admin-transaksi-data-table/ng-admin-transaksi-data-table.component.ngfactory';
import * as i3 from '../ng-admin-transaksi-data-table/ng-admin-transaksi-data-table.component';
import * as i4 from './ng-admin-transaksi.component';
const styles_NgAdminTransaksiComponent:any[] = [i0.styles];
export const RenderType_NgAdminTransaksiComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminTransaksiComponent,data:{}});
export function View_NgAdminTransaksiComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-transaksi-data-table',
      ([] as any[]),(null as any),(null as any),(null as any),i2.View_NgAdminTransaksiDataTableComponent_0,
      i2.RenderType_NgAdminTransaksiDataTableComponent)),i1.ɵdid(49152,(null as any),
      0,i3.NgAdminTransaksiDataTableComponent,([] as any[]),(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_NgAdminTransaksiComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-transaksi',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminTransaksiComponent_0,
      RenderType_NgAdminTransaksiComponent)),i1.ɵdid(49152,(null as any),0,i4.NgAdminTransaksiComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NgAdminTransaksiComponentNgFactory:i1.ComponentFactory<i4.NgAdminTransaksiComponent> = i1.ɵccf('app-ng-admin-transaksi',
    i4.NgAdminTransaksiComponent,View_NgAdminTransaksiComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tdHJhbnNha3NpL25nLWFkbWluLXRyYW5zYWtzaS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tdHJhbnNha3NpL25nLWFkbWluLXRyYW5zYWtzaS5jb21wb25lbnQudHMiLCJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vQ29tcG9uZW50cy9uZy1hZG1pbi10cmFuc2Frc2kvbmctYWRtaW4tdHJhbnNha3NpLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tdHJhbnNha3NpL25nLWFkbWluLXRyYW5zYWtzaS5jb21wb25lbnQudHMuTmdBZG1pblRyYW5zYWtzaUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxhcHAtbmctYWRtaW4tdHJhbnNha3NpLWRhdGEtdGFibGU+PC9hcHAtbmctYWRtaW4tdHJhbnNha3NpLWRhdGEtdGFibGU+XG4iLCI8YXBwLW5nLWFkbWluLXRyYW5zYWtzaT48L2FwcC1uZy1hZG1pbi10cmFuc2Frc2k+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtzREFBQSxVQUFBO01BQUE7TUFBdUU7OztvQkNBdkU7TUFBQTswQ0FBQSxVQUFBO01BQUE7OzsifQ==
