/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng-admin-ng-user.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../ng-admin-ng-user-form/ng-admin-ng-user-form.component.ngfactory';
import * as i3 from '../ng-admin-ng-user-form/ng-admin-ng-user-form.component';
import * as i4 from '../ng-admin-ng-user-data-table/ng-admin-ng-user-data-table.component.ngfactory';
import * as i5 from '../ng-admin-ng-user-data-table/ng-admin-ng-user-data-table.component';
import * as i6 from './ng-admin-ng-user.component';
const styles_NgAdminNgUserComponent:any[] = [i0.styles];
export const RenderType_NgAdminNgUserComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NgAdminNgUserComponent,data:{}});
export function View_NgAdminNgUserComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-ng-user-form',
      ([] as any[]),(null as any),(null as any),(null as any),i2.View_NgAdminNgUserFormComponent_0,
      i2.RenderType_NgAdminNgUserFormComponent)),i1.ɵdid(49152,(null as any),0,i3.NgAdminNgUserFormComponent,
      ([] as any[]),(null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-ng-user-data-table',
          ([] as any[]),(null as any),(null as any),(null as any),i4.View_NgAdminNgUserDataTableComponent_0,
          i4.RenderType_NgAdminNgUserDataTableComponent)),i1.ɵdid(49152,(null as any),
          0,i5.NgAdminNgUserDataTableComponent,([] as any[]),(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_NgAdminNgUserComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-ng-admin-ng-user',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgAdminNgUserComponent_0,
      RenderType_NgAdminNgUserComponent)),i1.ɵdid(49152,(null as any),0,i6.NgAdminNgUserComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NgAdminNgUserComponentNgFactory:i1.ComponentFactory<i6.NgAdminNgUserComponent> = i1.ɵccf('app-ng-admin-ng-user',
    i6.NgAdminNgUserComponent,View_NgAdminNgUserComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tbmctdXNlci9uZy1hZG1pbi1uZy11c2VyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9iYXJhbmcvc3JjL2FwcC9Nb2R1bGVzL25nQWRtaW4vQ29tcG9uZW50cy9uZy1hZG1pbi1uZy11c2VyL25nLWFkbWluLW5nLXVzZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tbmctdXNlci9uZy1hZG1pbi1uZy11c2VyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0FkbWluL0NvbXBvbmVudHMvbmctYWRtaW4tbmctdXNlci9uZy1hZG1pbi1uZy11c2VyLmNvbXBvbmVudC50cy5OZ0FkbWluTmdVc2VyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFwcC1uZy1hZG1pbi1uZy11c2VyLWZvcm0+PC9hcHAtbmctYWRtaW4tbmctdXNlci1mb3JtPlxuPGFwcC1uZy1hZG1pbi1uZy11c2VyLWRhdGEtdGFibGU+PC9hcHAtbmctYWRtaW4tbmctdXNlci1kYXRhLXRhYmxlPlxuIiwiPGFwcC1uZy1hZG1pbi1uZy11c2VyPjwvYXBwLW5nLWFkbWluLW5nLXVzZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBOzhDQUFBLFVBQUE7TUFBQSwyQ0FBdUQ7TUFDdkQ7VUFBQTt1REFBQSxVQUFBO1VBQUE7TUFBbUU7OztvQkNEbkU7TUFBQTt1Q0FBQSxVQUFBO01BQUE7OzsifQ==
