/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './fa-icon.component.scss.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i3 from '@angular/material';
import * as i4 from './fa-icon.component';
import * as i5 from '@angular/platform-browser';
const styles_FaIconComponent:any[] = [i0.styles];
export const RenderType_FaIconComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:2,
    styles:styles_FaIconComponent,data:{}});
export function View_FaIconComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'md-icon',[['class',
      'mat-icon'],['fontSet','fontawesome'],['role','img']],(null as any),(null as any),
      (null as any),i2.View_MdIcon_0,i2.RenderType_MdIcon)),i1.ɵdid(16384,(null as any),
      0,i3.MdPrefixRejector,[[2,i3.MATERIAL_COMPATIBILITY_MODE],i1.ElementRef],(null as any),
      (null as any)),i1.ɵdid(638976,(null as any),0,i3.MdIcon,[i1.Renderer2,i1.ElementRef,
      i3.MdIconRegistry,[8,(null as any)]],{fontSet:[0,'fontSet'],fontIcon:[1,'fontIcon']},
      (null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i4.FaIconComponent = _v.component;
    const currVal_0:any = 'fontawesome';
    const currVal_1:any = _co.faIcon;
    _ck(_v,2,0,currVal_0,currVal_1);
  },(null as any));
}
export function View_FaIconComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-fa-icon',
      ([] as any[]),(null as any),(null as any),(null as any),View_FaIconComponent_0,
      RenderType_FaIconComponent)),i1.ɵdid(114688,(null as any),0,i4.FaIconComponent,
      [i3.MdIconRegistry,i5.DomSanitizer],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const FaIconComponentNgFactory:i1.ComponentFactory<i4.FaIconComponent> = i1.ɵccf('app-fa-icon',
    i4.FaIconComponent,View_FaIconComponent_Host_0,{faIcon:'faIcon'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvQ29tcG9uZW50cy9mYS1pY29uL2ZhLWljb24uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL0NvbXBvbmVudHMvZmEtaWNvbi9mYS1pY29uLmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL0NvbXBvbmVudHMvZmEtaWNvbi9mYS1pY29uLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovYmFyYW5nL3NyYy9hcHAvQ29tcG9uZW50cy9mYS1pY29uL2ZhLWljb24uY29tcG9uZW50LnRzLkZhSWNvbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxtZC1pY29uIGZvbnRTZXQ9XCJmb250YXdlc29tZVwiIFtmb250SWNvbl09XCJmYUljb25cIj48L21kLWljb24+XG4iLCI8YXBwLWZhLWljb24+PC9hcHAtZmEtaWNvbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBLDZEQUFBO01BQUE7TUFBQSxzQkFBQTt3QkFBQTtNQUFBLGVBQTZEOztJQUFwRDtJQUFzQjtJQUEvQixXQUFTLFVBQXNCLFNBQS9COzs7O29CQ0FBO01BQUE7Z0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
