/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.fxContainer[_ngcontent-%COMP%] {\r\n	box-sizing: border-box !important;\r\n}\r\n.grey[_ngcontent-%COMP%]{\r\n	background-color: #EEE !important;\r\n}\r\n//\r\n\r\n.form.container[_ngcontent-%COMP%] {\r\n	margin-top: 10vh;\r\n}\r\n\r\n.mat-card[_ngcontent-%COMP%] {\r\n	background-color: #EEE;\r\n}\r\ndiv[_ngcontent-%COMP%]{\r\n	margin:0;\r\n	padding:0;\r\n}\r\nspan[_ngcontent-%COMP%] {\r\n	display: inline;\r\n}\r\n\r\n.full-width[_ngcontent-%COMP%] {\r\n	width: 100%;\r\n}\r\n\r\n.small[_ngcontent-%COMP%], .form-error[_ngcontent-%COMP%] {\r\n	font-size: 11px;\r\n}\r\n\r\n.form-error[_ngcontent-%COMP%] {\r\n	color: #F00;\r\n}\r\n\r\nbutton[ng-reflect-disabled=\'true\'][_ngcontent-%COMP%]:hover {\r\n	// cursor: none;\r\n	cursor: url(../../../../../assets/Cursors/cursor_click_x.cur) !important;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovYmFyYW5nL3NyYy9hcHAvTW9kdWxlcy9uZ0F1dGgvQ29tcG9uZW50cy9uZy1hdXRoLXVzZXIvbmctYXV0aC11c2VyLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L2JhcmFuZy9zcmMvYXBwL01vZHVsZXMvbmdBdXRoL0NvbXBvbmVudHMvbmctYXV0aC11c2VyL25nLWF1dGgtdXNlci5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
